### ISSUE TITLE
Move tests to espresso. 

### ISSUE THREAD

**Issue by ShivamPokhriyal** [dimagi/commcare-android#2341]
* [x] DeletedUser
* [x] FormEntry
* [x] Fixtures
* [x] MenuTests
* [x] Login
* [x] FormSettings
* [x] CaseSharing
* [x] Languages
* [x] CaseListSearch
* [x] CaseListSort
* [x] Settings
* [x] FormFiltering
* [x] Tiles
* [x] SessionExpiration
* [x] Dialogs
* [x] InstallList
* [x] DemoUserOnline
* [x] DemoUserOffline
* [x] LookupTableOptionSorting
* [x] ManualQuarantine
* [x] LogSubmission

**Comment by ShivamPokhriyal** [comment]
@shubham1g5 Since we've removed the manual quarantine option, will it be okay to not include `ManualQuarantine` in espresso?

**Comment by shubham1g5** [comment]
@ShivamPokhriyal  we still have manual quarantine , we have just added another step to enable this from advanced actions. So we should still make necessary changes for the new UI and implement it.

**Comment by ShivamPokhriyal** [comment]
Ohh great, I'll add it then.
