### ISSUE TITLE
Allow the use of a custom Barcode Scanning Application

### ISSUE THREAD

**Issue by ctsims** [dimagi/commcare-android#2377]
Right now we solely use the embedded zxing library, but there are circumstances where users might want to jump out to a much more powerful version that's more appropriate for their device or use case.

The need for this would be negated by implementing https://github.com/dimagi/commcare-android/issues/2321, but that's potentially a significantly larger scope of work compared to a fallback option for telling the barcode scanner to use the traditional zxing intent, rather than the built-in one. 

This seems to me like an App setting rather than a callout specific setting, so I think the best course of action would be to make it an [application preference](https://github.com/dimagi/commcare-android/blob/master/app/src/org/commcare/preferences/MainConfigurablePreferences.java) ("Use intent callout for scanner") that is loaded in the FormEntryActivity and passed into the [widget factory](https://github.com/dimagi/commcare-android/blob/master/app/src/org/commcare/views/widgets/WidgetFactory.java#L121) .

**Comment by shubham1g5** [comment]
@ShivamPokhriyal this would be good for us to prioritize on SAAS for 2.51 . Feel free to drop any questions here.
