### ISSUE TITLE
Not able to build commcare android 

### ISSUE THREAD

**Issue by siddesh13** [dimagi/commcare-android#2473]
Hello,
As I import commcare android in android studio I am not able to build project because of the following issue
Unable to resolve dependency for ':app@standaloneRelease/compileClasspath': Could not resolve io.ona.kujaku:library:0.7.2.
Could not GET 'http://dl.bintray.com/ona/kujaku/io/ona/kujaku/library/0.7.2/library-0.7.2.pom'. Received status code 403 from server: Forbidden
Please suggest
Thanks
Siddesh S

**Comment by ShivamPokhriyal** [comment]
Hi @siddesh13, Sorry to hear that the build is failing. 

Is your branch up to date with `master`? It seems like `Could not resolve io.ona.kujaku:library:0.7.2` is trying to use version `0.7.2` of kujaku and we're on version `0.8.7` currently. 

Have you made any changes to `commcare`?

**Comment by siddesh13** [comment]
Having same error  on master 
Could not GET 'http://dl.bintray.com/ona/kujaku/io/ona/kujaku/library/0.8.7/library-0.8.7.pom'. Received status code 403 from server: Forbidden

**Comment by shubham1g5** [comment]
It's probably due to [this](https://github.com/onaio/kujaku/issues/352), waiting for a response there. In the meanwhile you can try commenting this dependency and `BaseMapboxActivity` and it's subclasses to build.

**Comment by ekigamba** [comment]
@shubham1g5  Replied https://github.com/onaio/kujaku/issues/352#issuecomment-839698480

**Comment by siddesh13** [comment]
Could not GET 'https://maven.pkg.github.com/onaio/kujaku/io/ona/kujaku/library/0.9.0/library-0.9.0.pom'. Received status code 401 from server: Unauthorized

**Comment by ekigamba** [comment]
@siddesh13 Kindly make sure you have the github token configured and username with access to read-packages

**Comment by shubham1g5** [comment]
@siddesh13 this should be resolved now. Can you pull again and try. Thanks!
