### ISSUE TITLE
jcenter sunset, casing inability to build

### ISSUE THREAD

**Issue by jbylina** [dimagi/commcare-android#2825]
Due to jcenter sunset: https://jfrog.com/blog/jcenter-sunset/

The following dependencies fail to resolve, causing build failure:
* com.simprints:LibSimprints:1.0.12
* com.duolingo.open:rtl-viewpager:2.0.0
* com.mapbox.mapboxsdk:mapbox-android-accounts:0.2.0
* com.android.volley:volley:1.1.0
* com.snatik:storage:2.1.0
* io.realm:realm-android-library:4.1.1
* io.realm:realm-annotations:4.1.1

**Comment by jbylina** [comment]
@shubham1g5 As a quick fix can you add those jars into: `./app/libs`. Unfortunately, I don't have them cached in any way, so they are blocking the build.

**Comment by avazirna** [comment]
@jbylina thank you for bringing this to our attention, we will add this to the our backlog and see if we can prioritize it in the next few weeks. In the meantime, I can upload them to a gdrive folder and share it with you, how does that sound?

**Comment by shubham1g5** [comment]
@avazirna Probably better to put these in codebase in `libs` folder itself in short term as we don't want to have a broken `master` branch . I know that there are a few folks atleast who are dependent on `master` building correctly.

**Comment by jbylina** [comment]
+1 to @shubham1g5. It would be best to have it `libs` dir but I can work on gdrive contents. Thanks for all the help 😃

**Comment by avazirna** [comment]
@jbylina this is done. Can you update `master` and confirm that you can now build successfully?

**Comment by jbylina** [comment]
Works! `master` builds successfully. Thank you @avazirna :)
